spring.application.name=rentify
#spring.datasource.url=jdbc:mysql://localhost:3306/rentify_db
#spring.datasource.username=root
#spring.datasource.password=1234
spring.security.oauth2.client.registration.google.client-id=159066048192-6hlb11q3r2rv5od2td2esg3hirh0b4cr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.facebook.client-id=1093476335561966
spring.security.oauth2.client.registration.facebook.client-secret=9b4b077feb83f5510e340233909328aa

#spring.security.oauth2.client.registration.apple.client-id=com.rentify
#spring.security.oauth2.client.registration.apple.client-secret=secret

spring.datasource.url=jdbc:mysql://localhost:3306/retail?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alighaleb2001@gmail.com
spring.mail.password=rentify
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
